[workspace]
members = [
    "server",
    "tools"
]

[patch.crates-io]
eframe = { git = 'https://github.com/nmeylan/egui', rev = "cc7b299a132024dff44b53ccf8ca8c810764bea6" }
#egui_glow = { git = 'https://github.com/nmeylan/egui' }


[patch."https://github.com/nmeylan/rathena-script-lang-interpreter"]
#rathena_script_lang_interpreter = {path = "C:\\dev\\ragnarok\\ragnarok-script-interpreter"}
#rathena_script_lang_interpreter = {path = "/home/nmeylan/dev/ragnarok/ragnarok-script-interpreter"}