[package]
name = "server"
version = "0.1.0"
edition = "2018"

[dependencies]
byteorder = "1.4.3"
lazy_static  = "1.4.0"
regex = "1.5"
tokio = { version = "1.12", features = ["full"] }
futures = "0.3"
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "mysql" ] }
rand = "0.8"
sql = { path = "../lib/sql" }
accessor = { path = "../lib/accessor" }
flate2 = "1.0"
md5 = "0.7.0"
log = "0.4"
flexi_logger = "0.19"

[[bin]]
name = "packets"
path = "tools/packets/main.rs"
[[bin]]
name = "maps"
path = "tools/map-cache/main.rs"
