[package]
name = "server"
version = "0.1.0"
edition = "2018"

[dependencies]
byteorder = "1.4.3"
lazy_static  = "1.4.0"
maplit = "1.0.2"
regex = "1.5"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "mysql" ] }
rand = "0.8"
sql = { path = "../lib/sql" }
flate2 = "1.0"

[[bin]]
name = "packets"
path = "tools/packets/main.rs"
[[bin]]
name = "maps"
path = "tools/maps/main.rs"
